version: "3"

services:
  resource_postgres_db:
    image: postgres:latest
    container_name: resource_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: resource_service_db
      POSTGRES_USER: resource_user
      POSTGRES_PASSWORD: resource_password
    ports:
      - "5432:5432"
    volumes:
      - resource-postgres-data:/var/lib/postgresql/data

  song_postgres_db:
    image: postgres:latest
    container_name: song_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: song_service_db
      POSTGRES_USER: song_user
      POSTGRES_PASSWORD: song_password
    ports:
      - "5433:5432"
    volumes:
      - song-postgres-data:/var/lib/postgresql/data

volumes:
  resource-postgres-data:
  song-postgres-data: