services:
  postgres:
    image: postgres:latest
    container_name: resource_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: resource_service_db
      POSTGRES_USER: resource_user
      POSTGRES_PASSWORD: resource_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: