version: "3"

services:
  discovery-service:
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"

  resource_postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB_1}
      POSTGRES_USER: ${POSTGRES_USER_1}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_1}
    volumes:
      - resource-postgres-data:/var/lib/postgresql/data

  song_postgres_db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB_2}
      POSTGRES_USER: ${POSTGRES_USER_2}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_2}
    volumes:
      - song-postgres-data:/var/lib/postgresql/data

  resource-service:
    build:
      context: ./resource-service
    depends_on:
      - resource_postgres_db
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${RESOURCE_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_SPRING_DATASOURCE_PASSWORD}
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: ${EUREKA_URL}
    ports:
      - "8081:8081"

  song-service:
    build:
      context: ./song-service
    depends_on:
      - song_postgres_db
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: ${SONG_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SONG_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SONG_SPRING_DATASOURCE_PASSWORD}
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: ${EUREKA_URL}
    ports:
      - "8082:8082"

volumes:
  resource-postgres-data:
  song-postgres-data:

#    ports:
#      - "8082-8083:8082"
#    deploy:
#      replicas: 2