eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: api-gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/api/resource/**
          filters:
            - name: CircuitBreaker
              args:
                name: resourceService
                fallbackUri: forward:/fallback
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/api/songs/**
          filters:
            - name: CircuitBreaker
              args:
                name: songService
                fallbackUri: forward:/fallback
        - id: resource-processor
          uri: lb://resource-processor
          predicates:
            - Path=/processor/**
          filters:
            - name: CircuitBreaker
              args:
                name: resourceProcessor
                fallbackUri: forward:/fallback

server:
  port: 8989

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
  instances:
    resourceService:
      baseConfig: default
    songService:
      baseConfig: default
    resourceProcessor:
      baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
#  tracing:
#    sampling:
#      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans
#
#logging:
#  pattern:
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"