spring:
  application:
    name: song-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/song_service_db
    username: song_user
    password: song_password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      url: /v3/api-docs.yaml
      enabled: true
      path: /swagger-ui.html
server:
  port: 8082
